name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
projects: []
assignees:
  - SuperYoshi10000
body:
  - type: markdown
    attributes:
      value: "## Welcome!"
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - Latest
        - X.x.x
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - Internet Explorer
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: what
    attributes:
      label: Type of Problem
      description: Where do you think the problem is? Leave blank if you aren't sure.
      options:
        - label: Website Problem (visible to you)
        - label: Server Problem
        - label: Security Problem - _Consider reporting a [Security Vulnerability](https://github.com/SuperYoshi10000/LoginTest/security/advisories/new) instead. If showing details to others could be a problem, do not report the vulnerability as an issue._
  - type: dropdown
    id: importance
    attributes:
      label: Severity
      description: How big of a problem is this bug. How important is it that is is fixed?
      options:
        - "- Low"
        - "* Moderate"
        - ! High
        - ⚠ Critical
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
